apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: shruti-verma-v2-canary-app
description: main application pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles: []
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [25]
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: prod Run Service
run:
  location: projects/faa-gcp-training-14-kfa-0808/locations/us-central1
